### ISSUE TITLE
[meta] Progress Indicator for Sprite Downloader

### ISSUE THREAD

**Issue by miketrethewey** [Artheau/SpriteSomething#55]
Iteration
- [x] 1: Dialogue that counts the elements in the json file and tells the user that there's this many to download and it'll take a while
- [ ] 2: Dialogue that actually has a progress bar indicator and updates as it gets new sprites and prints the name of the sprite as it gets it
- [ ] 3: Pipe updates to status bar instead of a new window

**Comment by Artheau** [comment]
Should be sufficient for a 1.0 release to just have the warning dialogue without the progress bars and such, although the progress bars are more elegant.

**Comment by miketrethewey** [comment]
![](https://cdn.discordapp.com/attachments/483880468731789322/616444515284287497/unknown.png)
![](https://cdn.discordapp.com/attachments/483880468731789322/616444608355762210/unknown.png)

**Comment by miketrethewey** [comment]
https://github.com/aerinon/ALttPDoorRandomizer/blob/DoorDev/source/classes/SpriteSelector.py
